version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./results:/app/results
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "4001:80"
    depends_on:
      - app
