name: Deploy to Pages

on:
  push:
    branches: [ "staging" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IRACING_EMAIL: ${{ secrets.IRACING_EMAIL }}
      IRACING_PASSWORD: ${{ secrets.IRACING_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BASE_URL: "https://yvon.github.io/iracing-data-api-client/"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Download previous data
        uses: s3-actions/aws-cli@v1
        with:
          aws-command: s3 cp s3://iracing-data/data.tgz data.tgz
        continue-on-error: true

      - name: Extract data
        run: |
          mkdir -p data
          test -f data.tgz && tar -xzf data.tgz || echo "Missing artifact"

      - name: Build the site
        run: rake build

      - name: Compress data
        run: tar -czf data.tgz data

      - name: Archive data
        uses: s3-actions/aws-cli@v1
        with:
          aws-command: s3 cp data.tgz s3://iracing-data/data.tgz

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v1

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
