name: Deploy to Pages

on:
  push:
    branches: [ "main" ]
  # Every hour
  schedule:
    - cron: "30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IRACING_EMAIL: ${{ secrets.IRACING_EMAIL }}
      IRACING_PASSWORD: ${{ secrets.IRACING_PASSWORD }}
      BASE_URL: "https://yvon.github.io/iracing-data-api-client/"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Configure cache for data directory
        id: cache-data-dir
        uses: actions/cache@v3
        with:
          path: data/
          key: data-dir-${{ github.run_id }}
          restore-keys: |
            data-dir-

      - name: Build the site
        run: rake -j 4 update clean

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v1

  deploy:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
